// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHC8vGSV0qnGqpgdPoeJhznga7kg0Rw-c',
    appId: '1:407028479534:android:ee0518f7736e8d63c991bf',
    messagingSenderId: '407028479534',
    projectId: 'wister-lite-app',
    storageBucket: 'wister-lite-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB4gj6oOOF7XiogTl_mkDbZkEpm2veK0c',
    appId: '1:407028479534:ios:a4bc300a9eea9875c991bf',
    messagingSenderId: '407028479534',
    projectId: 'wister-lite-app',
    storageBucket: 'wister-lite-app.firebasestorage.app',
    androidClientId: '407028479534-aia5pri7ma9ag2f2dne85h3ldsvvpkhm.apps.googleusercontent.com',
    iosClientId: '407028479534-ae3ug087ddqrfrrbeap57ee29d8009im.apps.googleusercontent.com',
    iosBundleId: 'com.developerparera.wisterLite',
  );
}
